/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Dominio.Biblioteca;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gerar
 */
public class PrestamoInterfaz extends javax.swing.JFrame {
        public static String identificadorPrestamo = "";
        public static Biblioteca biblioteca;
        public static final int MATRICULA_INVALIDA = 3;
        public static final int ITEM_INVALIDO = 2;
        public static final int PRESTAMO_EXITOSO = 1;        
        public static final int ITEM_NO_DISPONIBLE = 0;
        public static final int PRESTAMO_FUERA_DE_LIMITE = -1;
        public static final int ACCION_CANCELADA = -2;

    /**
     * Creates new form prestamoInterfaz
     */
    public PrestamoInterfaz() {
        biblioteca = new Biblioteca();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Prestamo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        matriculaAlumnoCampo = new javax.swing.JLabel();
        identificadorItemCampo = new javax.swing.JLabel();
        matriculaAlumnoTexto = new javax.swing.JTextField();
        identificadorItemTexto = new javax.swing.JTextField();
        footerPanel = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JButton();
        botonAceptarPrestamo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matriculaAlumnoCampo.setText("Matrícula");

        identificadorItemCampo.setText("Identiificador del Item");

        matriculaAlumnoTexto.setText("jTextField1");

        identificadorItemTexto.setText("jTextField2");

        footerPanel.setBackground(new java.awt.Color(230, 230, 230));

        botonRegresar.setText("Regresar/Cancelar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonAceptarPrestamo.setText("Aceptar");
        botonAceptarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addComponent(botonRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptarPrestamo))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonRegresar)
                .addComponent(botonAceptarPrestamo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificadorItemCampo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(matriculaAlumnoCampo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificadorItemTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculaAlumnoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaAlumnoCampo)
                    .addComponent(matriculaAlumnoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificadorItemCampo)
                    .addComponent(identificadorItemTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        PanelPrincipal principal = new PanelPrincipal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAceptarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarPrestamoActionPerformed
        String identificadorItem = identificadorItemTexto.getText();
        String identificadorAlumno = matriculaAlumnoTexto.getText();
        int estadoPrestamo = 0;
        try {
            estadoPrestamo = realizarPrestamo(identificadorItem, identificadorAlumno);
            switch (estadoPrestamo) {
                case MATRICULA_INVALIDA:
                    JOptionPane.showMessageDialog(null, "La matricula introducide es inválida o no existe ese usuario", "Datos erroneos", JOptionPane.WARNING_MESSAGE);
                    break;
                case ITEM_INVALIDO:
                    JOptionPane.showMessageDialog(null, "El identificador del item es inválido", "Datos erroneos", JOptionPane.WARNING_MESSAGE);
                    break;
                case PRESTAMO_EXITOSO:
                    JOptionPane.showMessageDialog(null, "El préstamo se ha realizado con éxito.\n Caduca en la fecha "+biblioteca.verFechaFinPrestamo(identificadorPrestamo), "Préstamo correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case ITEM_NO_DISPONIBLE:
                    JOptionPane.showMessageDialog(null, "El item no está disponible", "Ocurrió un problema", JOptionPane.WARNING_MESSAGE);                
                    break;
                case PRESTAMO_FUERA_DE_LIMITE:
                    JOptionPane.showMessageDialog(null, "El usuario superó su límite de préstamos", "Ocurrió un problema", JOptionPane.WARNING_MESSAGE);
                    break;
                default:
            JOptionPane.showMessageDialog(null, "Lo lamentamos, ha ocurrido un error desconocido :(", "Ocurrió un problema", JOptionPane.WARNING_MESSAGE);
                    break;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lo lamentamos, ha ocurrido un error con la conexión a la Base de Datos", "Ocurrió un problema", JOptionPane.WARNING_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Lo lamentamos, el item no está registrado", "Ocurrió un problema", JOptionPane.WARNING_MESSAGE);
        }
        //if (estadoPrestamo)
    }//GEN-LAST:event_botonAceptarPrestamoActionPerformed

    private static int realizarPrestamo(String identificadorItem, String identificadorAlumno)throws SQLException{
        int estadoPrestamo = -2;
        if (biblioteca.verificarMatricula(identificadorAlumno)){
            if (biblioteca.verificarItem(identificadorItem)){
                int confirmacionPrestamo = JOptionPane.showConfirmDialog(null, "¿Está seguro?");
                if (confirmacionPrestamo == 0){
                    try {
                        identificadorPrestamo = biblioteca.generarPrestamo(identificadorItem);
                        estadoPrestamo = biblioteca.realizarPrestamo(identificadorPrestamo, identificadorAlumno);
                    } catch (SQLException ex) {
                        throw new SQLException("Hubo un error con la BD: " + ex.getMessage());                    
                    }
                }else{
                    estadoPrestamo = ACCION_CANCELADA;
                }
            }else{
                estadoPrestamo = ITEM_INVALIDO;
            }
        }else{
            estadoPrestamo = MATRICULA_INVALIDA;
        }
        return estadoPrestamo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrestamoInterfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarPrestamo;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel identificadorItemCampo;
    private javax.swing.JTextField identificadorItemTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel matriculaAlumnoCampo;
    private javax.swing.JTextField matriculaAlumnoTexto;
    // End of variables declaration//GEN-END:variables
}
