package interfaz;

import dominio.Biblioteca;
import dominio.Item;
import biblioteca.Util;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Interfaz visual que sirve para agregar préstamos a la base de datos
 *
 * @author Luis Fernando Gomez Alejandre
 * @author Francisco Gerardo Mares Solano
 * @since 06/06/2016
 */
public class ReservacionInterfaz extends javax.swing.JFrame{
    Item item;
    Biblioteca biblioteca;

    /**
     * Crea una nueva instancia de ReservacionInterfaz
     *
     * @param itemSeleccionado Recibe un Item para poder realizar la reservación enlazada a ese ítem
     * @throws java.sql.SQLException Informa que hay un error al conectar con la base de datos al usuario.
     */
    public ReservacionInterfaz(Item itemSeleccionado) throws SQLException{
        item = itemSeleccionado;
        biblioteca = new Biblioteca();
        initComponents();        
        setSize(660, 450);
        try{
            setInformacion();
            checarDisponibilidad();
        }catch (SQLException ex){
            throw new SQLException("Hubo un error con la BD: " + ex.getMessage());
        }
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Reservación");
    }

    /**
     * Muestra en la interfaz la información del ítem que se recibió. Esto es,
     * el autor del ítem, tipo de ítem, su título y la calificación que tiene.
     */
    public void setInformacion(){
        this.autorCampo.setText("Autor: " + item.getAutor());
        this.tipoMaterialCampo.setText("Tipo: " + item.getCategoria());
        this.tituloCampo.setText("Título: " + item.getTitulo());
        this.calificacionCampo.setText("Calificación: 9.5/10 ");
    }

    private void checarDisponibilidad() throws SQLException{
        boolean disponibilidad = Util.itemEstadoDisponibilidad(item.getIdentificador());
        botonAceptarReservacion.setEnabled(disponibilidad);
    }

    public ReservacionInterfaz(){
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Reservación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JButton();
        botonAceptarReservacion = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        tituloCampo = new javax.swing.JLabel();
        autorCampo = new javax.swing.JLabel();
        calificacionCampo = new javax.swing.JLabel();
        tipoMaterialCampo = new javax.swing.JLabel();
        informacionTabPanel = new javax.swing.JTabbedPane();
        comentarioPanel = new javax.swing.JPanel();
        informacionPanel = new javax.swing.JPanel();
        panelNavegacion = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        nombreBibliotecaCampo = new javax.swing.JLabel();
        tipoSistemaCampo = new javax.swing.JLabel();
        logoUv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(440, 370));
        getContentPane().setLayout(null);

        imagenPanel.setBackground(new java.awt.Color(140, 140, 140));

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(imagenPanel);
        imagenPanel.setBounds(200, 110, 100, 100);

        footerPanel.setBackground(new java.awt.Color(230, 230, 230));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonAceptarReservacion.setText("Reservar");
        botonAceptarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarReservacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addComponent(botonRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 496, Short.MAX_VALUE)
                .addComponent(botonAceptarReservacion)
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresar)
                    .addComponent(botonAceptarReservacion))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        getContentPane().add(footerPanel);
        footerPanel.setBounds(0, 390, 660, 30);

        panelDatos.setBackground(new java.awt.Color(230, 230, 230));

        tituloCampo.setText("Titulo:");

        autorCampo.setText("Autor:");

        calificacionCampo.setText("Calificación:");

        tipoMaterialCampo.setText("Tipo de material:");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCampo)
                    .addComponent(autorCampo)
                    .addComponent(calificacionCampo)
                    .addComponent(tipoMaterialCampo))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(tituloCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autorCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calificacionCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoMaterialCampo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(panelDatos);
        panelDatos.setBounds(310, 110, 305, 100);

        informacionTabPanel.setPreferredSize(new java.awt.Dimension(430, 144));

        javax.swing.GroupLayout comentarioPanelLayout = new javax.swing.GroupLayout(comentarioPanel);
        comentarioPanel.setLayout(comentarioPanelLayout);
        comentarioPanelLayout.setHorizontalGroup(
            comentarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        comentarioPanelLayout.setVerticalGroup(
            comentarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        informacionTabPanel.addTab("Comentarios", comentarioPanel);

        javax.swing.GroupLayout informacionPanelLayout = new javax.swing.GroupLayout(informacionPanel);
        informacionPanel.setLayout(informacionPanelLayout);
        informacionPanelLayout.setHorizontalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        informacionPanelLayout.setVerticalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        informacionTabPanel.addTab("Descripción", informacionPanel);

        getContentPane().add(informacionTabPanel);
        informacionTabPanel.setBounds(20, 230, 620, 144);

        panelNavegacion.setBackground(new java.awt.Color(230, 230, 230));

        nombreUsuario.setFont(new java.awt.Font("Raleway", 2, 14)); // NOI18N
        nombreUsuario.setText("¡Bienvenido/a, Xalaquia!");
        nombreUsuario.setToolTipText("Ésta es la sesión en la que te encuentras");

        javax.swing.GroupLayout panelNavegacionLayout = new javax.swing.GroupLayout(panelNavegacion);
        panelNavegacion.setLayout(panelNavegacionLayout);
        panelNavegacionLayout.setHorizontalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavegacionLayout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNavegacionLayout.setVerticalGroup(
            panelNavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavegacionLayout.createSequentialGroup()
                .addComponent(nombreUsuario)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(panelNavegacion);
        panelNavegacion.setBounds(0, 0, 660, 20);

        nombreBibliotecaCampo.setFont(new java.awt.Font("Raleway", 0, 36)); // NOI18N
        nombreBibliotecaCampo.setText("Universidad Veracruzana");
        getContentPane().add(nombreBibliotecaCampo);
        nombreBibliotecaCampo.setBounds(200, 30, 430, 50);

        tipoSistemaCampo.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tipoSistemaCampo.setText("Sistema Bibliotecario");
        getContentPane().add(tipoSistemaCampo);
        tipoSistemaCampo.setBounds(320, 80, 150, 18);

        logoUv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/Logo120x120.jpg"))); // NOI18N
        getContentPane().add(logoUv);
        logoUv.setBounds(40, 70, 90, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        SeleccionarItemInterfaz seleccionarInterfaz = null;
        try{
            seleccionarInterfaz = new SeleccionarItemInterfaz();
        }catch (SQLException ex){
            Logger.getLogger(ReservacionInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        seleccionarInterfaz.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAceptarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarReservacionActionPerformed
        int estadoReservacion = 0;
        String identificadorReservacion = "";
        try{
            identificadorReservacion = biblioteca.generarReservacion(item);
            estadoReservacion = biblioteca.realizarReservacion(identificadorReservacion);
            if (estadoReservacion == 1){
                botonAceptarReservacion.setEnabled(false);
                JOptionPane.showMessageDialog(null, "La reservación ha sido exitosa. \nPasa por el item en la fecha " + biblioteca.verFechaFinReservacion(identificadorReservacion), "Exito", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Ocurrio algo y la reservación falló ", "Reservacion erronea", JOptionPane.ERROR_MESSAGE);
            }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "No hay conexión con la Base de Datos ", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarReservacionActionPerformed

    /**
     * @param args posibles parámetros al main de la función
     */
    public static void main(String args[]){
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(ReservacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (InstantiationException ex){
            java.util.logging.Logger.getLogger(ReservacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (IllegalAccessException ex){
            java.util.logging.Logger.getLogger(ReservacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }catch (javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(ReservacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new ReservacionInterfaz().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorCampo;
    private javax.swing.JButton botonAceptarReservacion;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel calificacionCampo;
    private javax.swing.JPanel comentarioPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JPanel informacionPanel;
    private javax.swing.JTabbedPane informacionTabPanel;
    private javax.swing.JLabel logoUv;
    private javax.swing.JLabel nombreBibliotecaCampo;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelNavegacion;
    private javax.swing.JLabel tipoMaterialCampo;
    private javax.swing.JLabel tipoSistemaCampo;
    private javax.swing.JLabel tituloCampo;
    // End of variables declaration//GEN-END:variables
}
